FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs
RUN mkdir /application
WORKDIR /application

COPY Gemfile /application/Gemfile
COPY Gemfile.lock /application/Gemfile.lock

RUN gem install bundler
RUN bundle install
COPY . /application



CMD ["rails", "server", "-b", "0.0.0.0"]