FROM ruby:2.5
RUN apt-get update -qq && apt-get install -y nodejs
RUN mkdir /application
WORKDIR /application


ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

COPY Gemfile /application/Gemfile
COPY Gemfile.lock /application/Gemfile.lock

RUN gem install bundler
RUN bundle install
COPY . /application

EXPOSE 22

CMD ["rails", "server", "-b", "0.0.0.0"]